CREATE SEQUENCE "user_id_seq" INCREMENT BY 1 MINVALUE 1 START 1;
CREATE TABLE "user"
(
    id       INT          NOT NULL,
    email    VARCHAR(180) NOT NULL,
    roles    JSON         NOT NULL,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(180) NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username);
CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email);
